/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as IrrigationRouteImport } from './routes/irrigation'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAssistantRouteImport } from './routes/app.assistant'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppDiseaseRouteImport } from './routes/app.disease'
import { Route as AppFarmRouteImport } from './routes/app.farm'
import { Route as AppFertilizerRouteImport } from './routes/app.fertilizer'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppIrrigationRouteImport } from './routes/app.irrigation'
import { Route as AppMapRouteImport } from './routes/app.map'
import { Route as AppRecommendationsRouteImport } from './routes/app.recommendations'
import { Route as AppReportRouteImport } from './routes/app.report'
import { Route as AppRevenueRouteImport } from './routes/app.revenue'
import { Route as AppSensorsRouteImport } from './routes/app.sensors'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppWeatherRouteImport } from './routes/app.weather'
import { Route as AppWhatifRouteImport } from './routes/app.whatif'
import { Route as AppYieldRouteImport } from './routes/app.yield'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IrrigationRoute = IrrigationRouteImport.update({
  id: '/irrigation',
  path: '/irrigation',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppDiseaseRoute = AppDiseaseRouteImport.update({
  id: '/disease',
  path: '/disease',
  getParentRoute: () => AppRoute,
} as any)
const AppFarmRoute = AppFarmRouteImport.update({
  id: '/farm',
  path: '/farm',
  getParentRoute: () => AppRoute,
} as any)
const AppFertilizerRoute = AppFertilizerRouteImport.update({
  id: '/fertilizer',
  path: '/fertilizer',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppIrrigationRoute = AppIrrigationRouteImport.update({
  id: '/irrigation',
  path: '/irrigation',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppRecommendationsRoute = AppRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => AppRoute,
} as any)
const AppReportRoute = AppReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AppRoute,
} as any)
const AppRevenueRoute = AppRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AppRoute,
} as any)
const AppSensorsRoute = AppSensorsRouteImport.update({
  id: '/sensors',
  path: '/sensors',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppWeatherRoute = AppWeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => AppRoute,
} as any)
const AppWhatifRoute = AppWhatifRouteImport.update({
  id: '/whatif',
  path: '/whatif',
  getParentRoute: () => AppRoute,
} as any)
const AppYieldRoute = AppYieldRouteImport.update({
  id: '/yield',
  path: '/yield',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/irrigation': typeof IrrigationRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/disease': typeof AppDiseaseRoute
  '/app/farm': typeof AppFarmRoute
  '/app/fertilizer': typeof AppFertilizerRoute
  '/app/history': typeof AppHistoryRoute
  '/app/irrigation': typeof AppIrrigationRoute
  '/app/map': typeof AppMapRoute
  '/app/recommendations': typeof AppRecommendationsRoute
  '/app/report': typeof AppReportRoute
  '/app/revenue': typeof AppRevenueRoute
  '/app/sensors': typeof AppSensorsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/weather': typeof AppWeatherRoute
  '/app/whatif': typeof AppWhatifRoute
  '/app/yield': typeof AppYieldRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/irrigation': typeof IrrigationRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/disease': typeof AppDiseaseRoute
  '/app/farm': typeof AppFarmRoute
  '/app/fertilizer': typeof AppFertilizerRoute
  '/app/history': typeof AppHistoryRoute
  '/app/irrigation': typeof AppIrrigationRoute
  '/app/map': typeof AppMapRoute
  '/app/recommendations': typeof AppRecommendationsRoute
  '/app/report': typeof AppReportRoute
  '/app/revenue': typeof AppRevenueRoute
  '/app/sensors': typeof AppSensorsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/weather': typeof AppWeatherRoute
  '/app/whatif': typeof AppWhatifRoute
  '/app/yield': typeof AppYieldRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/irrigation': typeof IrrigationRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/disease': typeof AppDiseaseRoute
  '/app/farm': typeof AppFarmRoute
  '/app/fertilizer': typeof AppFertilizerRoute
  '/app/history': typeof AppHistoryRoute
  '/app/irrigation': typeof AppIrrigationRoute
  '/app/map': typeof AppMapRoute
  '/app/recommendations': typeof AppRecommendationsRoute
  '/app/report': typeof AppReportRoute
  '/app/revenue': typeof AppRevenueRoute
  '/app/sensors': typeof AppSensorsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/weather': typeof AppWeatherRoute
  '/app/whatif': typeof AppWhatifRoute
  '/app/yield': typeof AppYieldRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/irrigation'
    | '/login'
    | '/setup'
    | '/app/assistant'
    | '/app/calendar'
    | '/app/disease'
    | '/app/farm'
    | '/app/fertilizer'
    | '/app/history'
    | '/app/irrigation'
    | '/app/map'
    | '/app/recommendations'
    | '/app/report'
    | '/app/revenue'
    | '/app/sensors'
    | '/app/settings'
    | '/app/weather'
    | '/app/whatif'
    | '/app/yield'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/irrigation'
    | '/login'
    | '/setup'
    | '/app/assistant'
    | '/app/calendar'
    | '/app/disease'
    | '/app/farm'
    | '/app/fertilizer'
    | '/app/history'
    | '/app/irrigation'
    | '/app/map'
    | '/app/recommendations'
    | '/app/report'
    | '/app/revenue'
    | '/app/sensors'
    | '/app/settings'
    | '/app/weather'
    | '/app/whatif'
    | '/app/yield'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/irrigation'
    | '/login'
    | '/setup'
    | '/app/assistant'
    | '/app/calendar'
    | '/app/disease'
    | '/app/farm'
    | '/app/fertilizer'
    | '/app/history'
    | '/app/irrigation'
    | '/app/map'
    | '/app/recommendations'
    | '/app/report'
    | '/app/revenue'
    | '/app/sensors'
    | '/app/settings'
    | '/app/weather'
    | '/app/whatif'
    | '/app/yield'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  IrrigationRoute: typeof IrrigationRoute
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/irrigation': {
      id: '/irrigation'
      path: '/irrigation'
      fullPath: '/irrigation'
      preLoaderRoute: typeof IrrigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistant': {
      id: '/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/disease': {
      id: '/app/disease'
      path: '/disease'
      fullPath: '/app/disease'
      preLoaderRoute: typeof AppDiseaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/farm': {
      id: '/app/farm'
      path: '/farm'
      fullPath: '/app/farm'
      preLoaderRoute: typeof AppFarmRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fertilizer': {
      id: '/app/fertilizer'
      path: '/fertilizer'
      fullPath: '/app/fertilizer'
      preLoaderRoute: typeof AppFertilizerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/irrigation': {
      id: '/app/irrigation'
      path: '/irrigation'
      fullPath: '/app/irrigation'
      preLoaderRoute: typeof AppIrrigationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/map': {
      id: '/app/map'
      path: '/map'
      fullPath: '/app/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recommendations': {
      id: '/app/recommendations'
      path: '/recommendations'
      fullPath: '/app/recommendations'
      preLoaderRoute: typeof AppRecommendationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/report': {
      id: '/app/report'
      path: '/report'
      fullPath: '/app/report'
      preLoaderRoute: typeof AppReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/revenue': {
      id: '/app/revenue'
      path: '/revenue'
      fullPath: '/app/revenue'
      preLoaderRoute: typeof AppRevenueRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sensors': {
      id: '/app/sensors'
      path: '/sensors'
      fullPath: '/app/sensors'
      preLoaderRoute: typeof AppSensorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/weather': {
      id: '/app/weather'
      path: '/weather'
      fullPath: '/app/weather'
      preLoaderRoute: typeof AppWeatherRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/whatif': {
      id: '/app/whatif'
      path: '/whatif'
      fullPath: '/app/whatif'
      preLoaderRoute: typeof AppWhatifRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/yield': {
      id: '/app/yield'
      path: '/yield'
      fullPath: '/app/yield'
      preLoaderRoute: typeof AppYieldRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAssistantRoute: typeof AppAssistantRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppDiseaseRoute: typeof AppDiseaseRoute
  AppFarmRoute: typeof AppFarmRoute
  AppFertilizerRoute: typeof AppFertilizerRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppIrrigationRoute: typeof AppIrrigationRoute
  AppMapRoute: typeof AppMapRoute
  AppRecommendationsRoute: typeof AppRecommendationsRoute
  AppReportRoute: typeof AppReportRoute
  AppRevenueRoute: typeof AppRevenueRoute
  AppSensorsRoute: typeof AppSensorsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWeatherRoute: typeof AppWeatherRoute
  AppWhatifRoute: typeof AppWhatifRoute
  AppYieldRoute: typeof AppYieldRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssistantRoute: AppAssistantRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppDiseaseRoute: AppDiseaseRoute,
  AppFarmRoute: AppFarmRoute,
  AppFertilizerRoute: AppFertilizerRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppIrrigationRoute: AppIrrigationRoute,
  AppMapRoute: AppMapRoute,
  AppRecommendationsRoute: AppRecommendationsRoute,
  AppReportRoute: AppReportRoute,
  AppRevenueRoute: AppRevenueRoute,
  AppSensorsRoute: AppSensorsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWeatherRoute: AppWeatherRoute,
  AppWhatifRoute: AppWhatifRoute,
  AppYieldRoute: AppYieldRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  IrrigationRoute: IrrigationRoute,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
